TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to the model to test
  CHECKPOINT_TYPE: pytorch
DATA:
  PATH_TO_DATA_DIR: 'filenames/kinetics-40'
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5 
RESNET:
  ZERO_INIT_FINAL_BN: True
TSM:
  N_DIV: [[8, 8], [8, 8], [8, 8], [8, 8], [8, 8]]
  FUSION_N_DIV: [8, 8, 8, 8]
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001]
  STEPS: [0, 41, 72, 116]
  MAX_EPOCH: 160
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 40
  ARCH: slowfast
  MODEL_NAME: Student_SlowFast_MobileNetV3
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
TENSORBOARD:
  ENABLE: True
KD:
  ENABLE: True
  CONFIG: 'configs/final/TEACHER_SLOWFAST_NLN_8x8_MOBILENETV3.yaml'
  ALPHA: 0.9
  TEMPERATURE: 7
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: 'KD_SLOWFAST_8x8_MOBILENETV3_09'
